# Generated by Django 4.1.7 on 2023-04-17 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("rss_feed_url", models.URLField()),
                ("category", models.CharField(max_length=100)),
                (
                    "subscribers",
                    models.ManyToManyField(
                        related_name="subscriptions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("audio_file", models.FileField(upload_to="podcast_episodes/")),
                ("published_date", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("ad_timestamps", models.JSONField(blank=True, null=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="podcast_app.podcast",
                    ),
                ),
            ],
        ),
    ]
