# Generated by Django 4.1.7 on 2023-04-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="podcast_covers/"),
        ),
    ]
