# Generated by Django 4.1.7 on 2023-05-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast_app", "0002_podcast_cover"),
    ]

    operations = [
        migrations.RemoveField(model_name="podcast", name="category",),
        migrations.AlterField(
            model_name="podcast", name="cover", field=models.URLField(default=""),
        ),
    ]
