# Generated by Django 4.1.7 on 2023-05-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast_app", "0003_remove_podcast_category_alter_podcast_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="scanned_transcripts",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="transcription",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
