# Generated by Django 4.1.7 on 2023-05-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast_app", "0004_episode_scanned_transcripts_episode_transcription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="scanned_transcripts",
            field=models.TextField(blank=True, default=""),
        ),
    ]
