# Generated by Django 4.1.7 on 2023-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcast_app", "0005_alter_episode_scanned_transcripts"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="cuts",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
